[package]
name = "bgawk"
version = "0.1.0"
edition = "2021"
authors = ["amy universe <nopenullnilvoid00@gmail.com>"]
repository = "https://github.com/tomara-x/bgawk"
license = "MIT OR Apache-2.0"

[dependencies.bevy]
version = "0.15"
default-features = false
features = [
    "multi_threaded",
    "bevy_asset",
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_sprite",
    "tonemapping_luts",
    "x11",
]

[dependencies]
bevy_pancam = "0.16"
bevy_egui = "0.31"
egui = "0.29"
egui_extras = { version = "0.29", default-features = false, features = ["syntect"] }
avian2d = {version = "0.2", features = ["debug-plugin"]}
fundsp = {version = "0.20", git = "https://github.com/SamiPerttu/fundsp"}
cpal = {version = "0.15.3", features = ["jack"]}
syn = {version = "2.0", features = ["full", "extra-traits"]}
crossbeam-channel = "0.5"

# smol amount of optimization for our stuff
[profile.dev]
opt-level = 1

# high optimizations and no debug symbols for deps
[profile.dev.package."*"]
opt-level = 3
debug = false
debug-assertions = false

[profile.release]
panic = 'abort'
strip = true
codegen-units = 1
lto = "fat"
